# fly.toml app configuration file generated for url-tools on 2023-10-29T18:21:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "url-tools"
primary_region = "lhr"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
